# Generated by Django 4.0.5 on 2022-07-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama')),
                ('nilai_rata_rata', models.IntegerField(help_text='Dibulatkan dengan skala 1-100', verbose_name='Nilai Rata Rata')),
                ('penghasilan', models.IntegerField(choices=[('1', '>= 5 Juta'), ('2', '>= 4 Juta'), ('3', '>= 3 Juta'), ('4', '>= 2 Juta'), ('5', '>= 1 Juta')], verbose_name='Penghasilan Orang Tua')),
                ('tanggungan', models.IntegerField(choices=[(1, '1 Orang'), (2, '2 Orang'), (3, '3 Orang'), (4, '4 Orang'), (5, '>5 Orang')], verbose_name='Tanggungan Orang Tua')),
                ('organisasi', models.IntegerField(choices=[(4, 'Ikut'), (0, 'Tidak Ikut')], verbose_name='Ativitas Organisasi')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
            },
        ),
    ]
